// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geqdidodsdukzgvsxqev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcWRpZG9kc2R1a3pndnN4cWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTgyMzIsImV4cCI6MjA1ODU5NDIzMn0.HzY6Sd8mrLfJyHTowa-bxcut-XoGhIgha9uOa8l6bcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);